development:
  clients:
    default:
      uri: mongodb+srv://dbuser:dbpass@cluster0-tywqg.mongodb.net/test?retryWrites=true&w=majority
      options:
        server_selection_timeout: 5
  options:
    raise_not_found_error: false      

